#! /usr/bin/env python
# -*- coding:utf-8 -*-

import os
import sys

from modules.extension import by_extension
from modules.date import by_cdate, by_mdate


OPTION = {
    "extension": by_extension,
    "cdate": by_cdate,
    "mdate": by_mdate,
}


def main():
    try:
        _, source, target, key = sys.argv
        source = os.path.abspath(source)
        target = os.path.abspath(target)
        if not os.path.isdir(source):
            print "Wrong source path."
        else:
            if not os.path.isdir(target):
                os.makedirs(target)

            if key.lower() in OPTION:
                OPTION[key.lower()](source, target)
            else:
                print "Unknown key."

    except ValueError:
        print "You must provide all the parameters."


if __name__ == '__main__':
    main()
